In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Data Analytics environment is ready!")

Data Analytics environment is ready!

In [3]:
# Load the dataset

file_path = "../data/Online Retail.xlsx"

df = pd.read_excel(file_path)

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [4]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [5]:
df.shape

(541909, 8)

In [6]:
df.columns.tolist()

['InvoiceNo',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'UnitPrice',
 'CustomerID',
 'Country']

In [7]:
[
    'InvoiceNo',
    'StockCode',
    'Description',
    'Quantity',
    'InvoiceDate',
    'UnitPrice',
    'CustomerID',
    'Country'
]

['InvoiceNo',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'UnitPrice',
 'CustomerID',
 'Country']

In [8]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(5268)

In [10]:
df_raw = df.copy()

print("Original dataset:", df_raw.shape)

Original dataset: (541909, 8)

In [11]:
df = df.drop_duplicates().copy()

print("After removing duplicates:", df.shape)

After removing duplicates: (536641, 8)

In [12]:
df[df["CustomerID"].isnull()].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.00,NaN,United Kingdom
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,2010-12-01 14:32:00,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,2010-12-01 14:32:00,1.66,NaN,United Kingdom

In [13]:
df[df["Description"].isnull()].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom

In [14]:
df = df.dropna(subset=["Description"]).copy()

print("After handling missing descriptions:", df.shape)

After handling missing descriptions: (535187, 8)

In [15]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     133583
Country             0
dtype: int64

In [16]:
df["InvoiceNo"].astype(str).str.startswith("C").sum()

np.int64(9251)

In [17]:
(df["Quantity"] < 0).sum()

np.int64(9725)

In [18]:
(df["UnitPrice"] <= 0).sum()

np.int64(1058)

In [19]:
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

In [20]:
df[["Quantity", "UnitPrice", "Revenue"]].head()

   Quantity  UnitPrice  Revenue
0         6       2.55    15.30
1         6       3.39    20.34
2         8       2.75    22.00
3         6       3.39    20.34
4         6       3.39    20.34

In [21]:
df_raw = df.copy()

print("Original dataset:", df_raw.shape)

Original dataset: (535187, 9)

In [22]:
df = df.drop_duplicates().copy()

print("After removing duplicates:", df.shape)

After removing duplicates: (535187, 9)

In [23]:
df[df["CustomerID"].isnull()].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom,2.51
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom,5.02
1445,536544,21786,POLKADOT RAIN HAT,4,2010-12-01 14:32:00,0.85,NaN,United Kingdom,3.40
1446,536544,21787,RAIN PONCHO RETROSPOT,2,2010-12-01 14:32:00,1.66,NaN,United Kingdom,3.32
1447,536544,21790,VINTAGE SNAP CARDS,9,2010-12-01 14:32:00,1.66,NaN,United Kingdom,14.94

In [24]:
df = df.dropna(subset=["Description"]).copy()

print("After handling missing descriptions:", df.shape)

After handling missing descriptions: (535187, 9)

In [25]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     133583
Country             0
Revenue             0
dtype: int64

In [26]:
df["InvoiceNo"].astype(str).str.startswith("C").sum()

np.int64(9251)

In [27]:
(df["Quantity"] < 0).sum()

np.int64(9725)

In [28]:
(df["UnitPrice"] <= 0).sum()

np.int64(1058)

In [29]:
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

In [30]:
df[["Quantity", "UnitPrice", "Revenue"]].head()

   Quantity  UnitPrice  Revenue
0         6       2.55    15.30
1         6       3.39    20.34
2         8       2.75    22.00
3         6       3.39    20.34
4         6       3.39    20.34

In [31]:
# Create final clean dataset for sales analysis

df_clean = df.copy()

# Remove cancelled transactions
df_clean = df_clean[
    ~df_clean["InvoiceNo"].astype(str).str.startswith("C")
]

# Keep only positive quantities
df_clean = df_clean[df_clean["Quantity"] > 0]

# Keep only positive unit prices
df_clean = df_clean[df_clean["UnitPrice"] > 0]

# Reset index
df_clean = df_clean.reset_index(drop=True)

print("Final clean dataset shape:", df_clean.shape)

Final clean dataset shape: (524878, 9)

In [32]:
df_clean.isnull().sum()

InvoiceNo           0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     132186
Country             0
Revenue             0
dtype: int64

In [33]:
(df_clean["Quantity"] <= 0).sum()

np.int64(0)

In [34]:
(df_clean["UnitPrice"] <= 0).sum()

np.int64(0)

In [36]:
df_clean["InvoiceNo"].astype(str).str.startswith("C").sum()

np.int64(0)

In [37]:
df_clean["Revenue"].describe()

count    524878.000000
mean         20.275399
std         271.693566
min           0.001000
25%           3.900000
50%           9.920000
75%          17.700000
max      168469.600000
Name: Revenue, dtype: float64

In [38]:
# Convert InvoiceDate to datetime
df_clean["InvoiceDate"] = pd.to_datetime(df_clean["InvoiceDate"])

# Create date-related columns
df_clean["Year"] = df_clean["InvoiceDate"].dt.year
df_clean["Month"] = df_clean["InvoiceDate"].dt.month
df_clean["MonthName"] = df_clean["InvoiceDate"].dt.month_name()
df_clean["Day"] = df_clean["InvoiceDate"].dt.day
df_clean["Weekday"] = df_clean["InvoiceDate"].dt.day_name()

In [39]:
df_clean[
    [
        "InvoiceDate",
        "Year",
        "Month",
        "MonthName",
        "Day",
        "Weekday"
    ]
].head()

          InvoiceDate  Year  Month MonthName  Day    Weekday
0 2010-12-01 08:26:00  2010     12  December    1  Wednesday
1 2010-12-01 08:26:00  2010     12  December    1  Wednesday
2 2010-12-01 08:26:00  2010     12  December    1  Wednesday
3 2010-12-01 08:26:00  2010     12  December    1  Wednesday
4 2010-12-01 08:26:00  2010     12  December    1  Wednesday

In [40]:
total_revenue = df_clean["Revenue"].sum()
total_quantity = df_clean["Quantity"].sum()
total_orders = df_clean["InvoiceNo"].nunique()
total_products = df_clean["StockCode"].nunique()
total_countries = df_clean["Country"].nunique()

print("Total Revenue:", round(total_revenue, 2))
print("Total Quantity Sold:", total_quantity)
print("Total Orders:", total_orders)
print("Total Products:", total_products)
print("Total Countries:", total_countries)

Total Revenue: 10642110.8
Total Quantity Sold: 5572420
Total Orders: 19960
Total Products: 3922
Total Countries: 38

In [41]:
total_customers = df_clean["CustomerID"].nunique()

print("Unique Customers:", total_customers)

Unique Customers: 4338

In [42]:
# Save the cleaned dataset

output_path = "../data/online_retail_clean.csv"

df_clean.to_csv(output_path, index=False)

print("Cleaned dataset saved successfully!")
print("File:", output_path)

Cleaned dataset saved successfully!
File: ../data/online_retail_clean.csv

In [43]:
# Verify the saved dataset

df_test = pd.read_csv("../data/online_retail_clean.csv")

print("Saved dataset shape:", df_test.shape)
print("Saved dataset columns:", len(df_test.columns))

Saved dataset shape: (524878, 14)
Saved dataset columns: 14

C:\Users\fazil\AppData\Local\Temp\ipykernel_7964\190974393.py:3: DtypeWarning: Columns (0: InvoiceNo) have mixed types. Specify dtype option on import or set low_memory=False.
  df_test = pd.read_csv("../data/online_retail_clean.csv")

In [44]:
df_clean.columns.tolist()

['InvoiceNo',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'UnitPrice',
 'CustomerID',
 'Country',
 'Revenue',
 'Year',
 'Month',
 'MonthName',
 'Day',
 'Weekday']

In [45]:
df_clean.shape

(524878, 14)

In [46]:
df_clean.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Year,Month,MonthName,Day,Weekday
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,2010,12,December,1,Wednesday
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,December,1,Wednesday
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,2010,12,December,1,Wednesday
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,December,1,Wednesday
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,December,1,Wednesday

In [47]:
df_clean.columns.tolist()

['InvoiceNo',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'UnitPrice',
 'CustomerID',
 'Country',
 'Revenue',
 'Year',
 'Month',
 'MonthName',
 'Day',
 'Weekday']

In [48]:
cleaning_summary = pd.DataFrame({
    "Stage": [
        "Original dataset",
        "After duplicate removal",
        "After missing Description removal",
        "After removing cancelled transactions",
        "After removing non-positive quantities",
        "After removing non-positive prices"
    ],
    "Rows": [
        541909,
        536641,
        535187,
        len(df[~df["InvoiceNo"].astype(str).str.startswith("C")]),
        len(df[(~df["InvoiceNo"].astype(str).str.startswith("C")) & (df["Quantity"] > 0)]),
        len(df_clean)
    ]
})

cleaning_summary

                                    Stage    Rows
0                        Original dataset  541909
1                 After duplicate removal  536641
2       After missing Description removal  535187
3   After removing cancelled transactions  525936
4  After removing non-positive quantities  525462
5      After removing non-positive prices  524878

In [50]:
df_clean.columns.tolist()

['InvoiceNo',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'UnitPrice',
 'CustomerID',
 'Country',
 'Revenue',
 'Year',
 'Month',
 'MonthName',
 'Day',
 'Weekday']

In [51]:
df_clean.shape

(524878, 14)

In [54]:
df_clean.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Year,Month,MonthName,Day,Weekday
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,2010,12,December,1,Wednesday
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,December,1,Wednesday
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,2010,12,December,1,Wednesday
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,December,1,Wednesday
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,12,December,1,Wednesday

In [55]:
df_clean.columns.tolist()

['InvoiceNo',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'UnitPrice',
 'CustomerID',
 'Country',
 'Revenue',
 'Year',
 'Month',
 'MonthName',
 'Day',
 'Weekday']